### ISSUE TITLE
Link to help translate is misleading

### ISSUE THREAD

**Issue by niccokunzmann** [CoderDojo/coderdojo.com#38]
the link to the translations on the pages https://coderdojo.com/ and zen.coderdojo.com is wrong.

It should be https://crowdin.com/profile/coderdojo
and not
https://help.coderdojo.com/hc/en-us/articles/115002700443-Help-CoderDojo-with-translation
which points to
https://help.coderdojo.com/hc/en-us/articles/115002702123-Using-CrowdIn-Our-translation-tool
which points to
https://crowdin.com/project/zen-community-platform
which is outdated.

This link for all platforms should be used on both platforms so people know that there exist multiple sources for what they may want to translate. Otherwise, I click on the same link on coderDojo.com, translate everything and ask myself why zen ist not translated.

Roadmap:
- [ ] coderdojo.com #39 
- [ ] zen.coderdojo.com

**Comment by conoramurphy** [comment]
This issue is out of date as we want to point people to https://help.coderdojo.com/hc/en-us/articles/115002700443-Help-CoderDojo-with-translation so we can help onboard new people with translations.
