### ISSUE TITLE
Homepage: Dojo count incorrect on `en` version

### ISSUE THREAD

**Issue by Jonic** [CoderDojo/coderdojo.com#52]
The number of Dojos is incorrect on the English home page, but is accurate on the other language versions.

**Comment by DanielBrierton** [comment]
So, this is actually because the site hasn't been rebuilt in over a month. If you go directly to say coderdojo.com/fr-FR you see the old count too.

I've set up a Zap to rebuild the site each day so the number gets updated. I reckon that's the best solution for now.
